const timeline = 
[
    {
        when: "2020-09-13",
        heading: "Assembly",
        image: "https://lh3.googleusercontent.com/FobhHeR3Ndb5a92OxtFyncz4bsP-UomK05h79vBPpiL7uskdzcIqKsPqDL8tSx5LZdcuu6pKikg0067I7-6RjPIND-89J-fROwEcCaNb8OKaER-VMl0EaKNlfxXS17bK0WCwkQ4g2F-KBS7KdKx-DKLxJyAwoTQwlYv1E7-agXkAtR-qKnI9lYyGSWzMmGoLiSoXcGVSbdSrjglzdYAzr53H5TNThXGo1xnL5UOd7y9d6b64eL5yljhDMyvJWBYNmUrznHCyz4G-9cM5M6dhtjjebfXrrVE3GMRLUvQbXRU9cFsysSS8q6QzdF7hdyJxhw7isOCOpHJ5setyKun6jAioNc2FWNbJXVNPW6HXJhTQdwJIUYSDxw5dv7_6UTNptGrBS3ZeKNqZrSKgpie-1on6TtvmD1cbSSVczQGUbwCbjpu92VV0g095pquEj-z2ibt6bmuJoZngMk-lNWKmRVKtpXBbLhhTciCrENidmtrIbO6S7OQDtdJuGLVkrhvRNXcxvCZUib4evde8HLpQFJ-FtPFoltQoRXHtwJTsEX8LRh2jkeJwexovsUc6RiBfLbEtzOjTyYvZMXulVJnC7jnRTHopMKO14AolWV-ldTd8jA1Suy-k3KO5G7QrVcp0IIzMBbtZdly3-_tLky8zrQEGxp085wftcnJVDihu60f0L7BWANQYMZQKhsDD2bA=w501-h890-no?authuser=0", 
        text: "Three units taking shape now. First task for each one is to position the speakers. The middle-sized on is the prototype, so I had already done this. The other two are similar, but each unit has a different combination of speaker sizes for individuality. The plan is to position the multiple units in separate parts of the room, but I actually quite like the way these units look clustered together. It makes me thing the speaker positioning should be random, rather than regular and predictable as they are here. Next task is to take the speakers off, put other bits of wood on for mounting the electronics later, then sand and paint in bright colours. Because why not."
    },
    {
        when: "2020-09-11",
        heading: "Next vertical unit",
        image: "https://lh3.googleusercontent.com/kW6inmUdAbui1UqaX4fx2kfKvqMWxECSB-3CstMvQHECotFcnpNL4wut8cOvFK9D6OnxKfOf4xAuoJbWSASG-qp0zt_S6JVpO6DVFqoN-Qv1hMBUQVDoAs1o5n6Oz3-h1cPRpDnNo8_0Vld4-Kd4aXSqqCHSKcuOiP0W74EGfAm4dxyKYyQhELaaIxdQ1plng7bOyE3Ue0144us5ecrhNVOr5UcsiLu1XajjuF1TF4BA1LPZ1Q-joLjVS2mTztVk8XHZmuIRxiizVInQ4_Bjw-wPlMLyA10v0HUk1HVjCYU4rtvw_wGEqRg9V71g2rHvZOON22IGkp7iQ529MFYlGjPL92BJKnDj0kIASJxE0qpLG_Go5ucj50KItq_HSQn05Fq9hqHLNImPiQ5FwvrTm5VOSW4kt3HuDGdneCtRCrrnf9jC_TVrlIL4eCIFXyW3_of7fFz5vCSl8J3eaNHRHXgn3rvH2cd6FzWX8ypLU2-NZatzAsIfl1RlOg-Tfb4m_hsLJc8zALMlIqZry7ilo6OnsBseXfG6v9_T54wY9CTZvgG7UIF7qcNmlq5wB5WjO5P-R3P8bhHNs07ToYIGLcar9RpcAuARJlRgV0rf1AGn46n5oMaYALhU0LWzbHzoM5XLkUpFNMCWTvsVy187-PmYIU5QygbM-I4JZKIALv6bWOli5tpthUnrAPC7pGs=w496-h881-no?authuser=0",
        text: "Back to the dry land idea, having enjoyed listening to one of these, time to start putting together more of them. Target is three for now, for which I will see if I can arrange some kind of showing in London. Maybe get a video together first. It strikes me the audio should be a field recording. It will be almost impossible to capture the ambient sound distribution from having three (nevermind several) of these positioned around a room, and a normal stereo recording is going to sound too perfect an impression of the wrong thing. One idea I had is to mount a couple of tiny mics onto each unit and let each make its own room/field recording from its perspective, then mix those in the stereo image depending on where the camera is pointing."
    },
    {
        when: "2020-09-09",
        heading: "Mental notes",
        image: "https://lh3.googleusercontent.com/urMZyrsx4Id77JDrQuzLQN3rZM57IFTZsVxCgKqDLVsnM8cISolfVeoybQHYMTBgq4SgqJcic1ZnIdx914wLuR4TK-rDv4lot1ARvEMhcj5Ii7BkiF6GlEm77lzs-tBY-COlWQxubDrgr5mNi3XlFgA40M07okpPvLVkBpjtNUrhfVD-cir3zIjWWkVaQ6HVgvzYyRE3cQ36-e863FgP1pYmiOCEU0EBQgatXsuZq6rTy0H6jf_2ABx4wRzA4Evle5nudGHr64-TMwVoJVsRWCO5s9gz7dxNXr7hLi3xLDv8h5oaW6bi854yOPjrghxzrJIkCd_289PF229CAFIfTrhQe3cbPFDyyFxaea3DU73YjF6lQ-RjkzXwaZz6Gtu3sLuLthBlOMGMQOV0iNCBCijmRwN_ZVJEFIPOKI5SCkea0uTk7AL5rEt3N45ie21NoL8arwhtxrTxmgEsGh9nJ0eyYT9lJ7HhWphhLNFVaH8l4y2T4tOrZgfnnf7K0VxCnbZ5PnoIKjFM4fBpLjlRU7i7L_Bsvv6ynDDBP2_4Ycu9-cxYXlNLQO7765qYPQ1r7JbDZSp0X-AEZi6KqJVN3WlHswVrbh_6lh5n1GYXeFPzpBlr9bxTrA3nJM9OXiPVStXd_ANUDHjBceu0inHe8IEvMr3GQEX79e9-h0lLnCdJZI6cUGkiYKNs2hhIjIA=w1070-h602-no?authuser=0",
        orientation: "landscape",
        text: "This looks like a nice spot for it. The acoustics under the first bridge are sweet, and the traffic noise from above might even complement the sounds. What to call it though - Water Music For Randomatones? Randomaquatones? Also somehow I have to get these things to float. My heaviest 12V batteries are 5.5Kg. That's going to need a big tyre."
    },
    {
        when: "2020-09-08",
        heading: "Floating an idea",
        image: "https://lh3.googleusercontent.com/oPTE6yb20iLU45_Bf0OqAdG0bia6uQYOZLZfNKAkoLStl4D9xSjSvuUshkoNz6Lf97Jhy3FNDBnAmRMzwiy4WACZ3No5AvQweWTTTe9ZeM8D-3uHLcSpmpSVNPshea5j6mDctS7Tm9wME4o1U4dNtYam5kM5CsvPmo1Y1LQ97XKmL6AYxCVR-iI4D4CXojY4IpdG_CP0bZkoP4rnaEpbU9-12xadWD9_TuLNdy1jkCozgaYB3gmloR1jXnwqvVNIjo5MKWwL6PNMqI46yoIxhWSzTGj_oB8tulYuOdm-9DMvJxdCSUuwx4q4rpaCpVpvz23IIGoXDoVnDwssffOBwYmD3M5h0OAENE3x6SVjbGLZQVj61Im4BE5EvkrkcNttBDG0rSfT8KPmbe4M0D2rLdURkxWpR-jWPNfDyKpw2VSVfUMyop9f7EkcumnyyBcnRZEKeaw2cOqbFGMfymDEWpoCHjlWeGFwib4xr41G0lLlp39UKduLUcUE9LD5aegttqr4PCWV8wNPMXFy0QMHMeT7I_vjTBwywU2Ofwg57Zo2hzNbf-dHXQzLFWA-Eh23xJ2zQQsfD7MucIkrSc0v4OgUTwM_7-8vzC18lsI1tohL_tqHZ_U_lP4wl9rIWD01xa27Wqd9es9DggiieBHlPcHAvlXSRcLbRmcYag13DZToX55ITgowSEdIaH7sQrA=w1070-h602-no?authuser=0",
        orientation: "landscape",
        text: "An eventful week of blowing up a Raspberry Pi and an amp. Tried a new smaller RPi (model A+) and found it had some glitches, but these could be reproduced simply by adjusting the system volume, so I'm not confident about the analogue output. Needing replacement amp as well I went for a HifiBerry Pi \"hat\", which is entirely digital and will thus bypass all the RPi audio bits which I think are the issue. Also, brilliantly, it takes 12V but will do the step down to 5V itself for the RPi. This will save me having to have an extra unit with wiring issues. Tried it all out after the necessary config changes in the RPi to tell it where its audio has to go. Not only does everything work, the audio is basically clean. Needs a volume control though, without a keybaord or a mouse. Hmm! In a totally unrelated flight of consciousness, I have begun pursuing the crazy idea of making a set of these units that will float. This would be the basic chassis, and one way of making it float might be to use the inner tube of a car tyre. So I've ordered one. I might work on this frame idea a bit more. I'm pleased with my elementary woodworking skills to have made this item, which at least looks like it fits together."
    },
    {
        when: "2020-08-28",
        heading: "Trying out the prototype",
        image: "https://lh3.googleusercontent.com/CoEOJ_7ke1bsRKkagusujk8wpTKos0DOhXHdtMmA2T_c6XzALC-jVPmW59RoEWnsiArHwHizi0EAJEumbTbCDZJUyugD_u7IZoxJM-isiXMtfIjv41ADkXcbwrH_bu6E7Y5odPwRUquiwlp2tCreXXI00pRtB4Hjz-V8Oi6TDX2RTi8vicXim51PQ4Ep2VvuG4_esa0I0lJ5iwx5O1l1bINH6sz0tUvAmiqdFIf-diEwGKtC9ee2tu6_C95uxuZ0Yizgx51n8Tr9heWHn7jZrHJv3Jnt_JQBxZloEBkKifLyqNCCFGtd05fldOr7SVJ9-LhxQHD8ZwPq_mHX4ajgzbatzTCUje9fNfDjZm5z8P0V-lyT8d7paNGTdYoYgFh3wgvIt_p8Op6nqv3htMS9n3jHUltFA3xisgZ_7az3hxavwaPG2BUz7AB4Kii99qwSFpfG0HYjRp6FttqlsYfvmDFYLPdRQUYdZEDklgCqhw04bZOcDpk7oIMosANPFcUX3zID47q9SY7R7YJcIt_kkc5X_IP1L-91rSWrU_okWlPWzbCk1D4m6jYOV7Om_1FIpoOqJrxWahtptpKnqKzWGPOQ4O0DMZs0Jqmja5XvkVD7VNUhrsjY-IqundsQC2d6id-LqDo0P6ERFF-gzfqbPzjHg6XuD2wZpCvv77KoYmdIfq6FfUZdP-TRa7kWLPE=w496-h881-no?authuser=0",
        text: "The prototype again, reconstructed with only three vertical posts, as I realised the fourth was unnecessary and in the way. Tried the sound generator, essentially everything works, with some issues. Audio playback has glitches, and there is a lot of interference noise. One issue might be the 12V-5V converter, as I've heard this kind of noise before when combining audio signals from things with different switch mode PSUs. Anyway I tried a USB audio interface just to rule out the RPi onboard DAC. Slightly quieter. Reduced noise significantly by not using 12v-5v stepdown, instead powering the RPi from a regular mains PSU. Got noise at all running it from two separate batteries. Joining the battery grounds made a load of noise reappear. Joining the +ves also made noise appear. Tried a different 12V-5V converter from the car, same result." 
    },
    {
        when: "2020-08-19",
        heading: "Randomatone One",
        image: "https://lh3.googleusercontent.com/2lx0sfEZ1BZnWJZrO2HbgvbSTvK8h_AnNymgg9keG1uBOT4ijiYpvnCd0j1sUlLgfRxE-fDLwosHdIRoBpBiB2qBw_cSLBQ1cXIkNwOkbIF5X2BuX7Ce41xakdOoc39EklRqB_fzyepconAGLerAP900hjWXku0pwHIYOU_M49aBIZDOoRyHeKGIL2WxhviYjmw10eHLf-z9HW5FtTWR0cjsXuWsmPHoGb85O7C4sMblZgX6FCu78AiY4YZDwNjKprQCx255gxjOh_fdWE--zarwWiHVzf6T-UZAyD8yQzkwicBMX2YvfQXxjg2u0ZrDrXPdhwnljJU542KLm627a9so5zZdhOGtoTzt_tkh5FOZCoDCVfjOGLKG6vlbUgjqepy3ywOKkt2NLoxKqwZgDcxZIDsXrxWguv3YttOm6TyOeNtTSKNT53vhkudy4-hjYi3i_KsURqsbB1lvBYsbr2VMXx5T8XyYaCIGC2XBmzfXrPCNDazVX85JD3gKxfp7r8yECGZ3yiLolgv00ke6bfGC7yVvRy2uVac10k4G4UOlNpB2g1bMJzsqZ2FXJafBg_XZXzi0Mc4BmeVJakoi_VN9vw5Q6JeYv32uhZCa6Kq16clUp6P2Pn91mQEVps9pHhMCXiBOCLSkW6CY8zRgTyWRDgfXMYjzoy98bRGBBbQJ5TVMPLEVqs1YZXnGu8s=w496-h881-no?authuser=0", 
        text: "Assembled prototype. You can just see that behind the circuit boards is a massive 12V 20Ah battery, the kind you find in a mobility scooter. This powers the Raspberry Pi via a step-down to 5V, and a 2x20W amp, currently driving two cheap speakers from Halfords. I've been preparing the software for this for some time now and had it working on a regular linux machine, and have tried it out on the RPi by itself over Wifi, not in this assembly yet."
    }
];
